baseURL = "https://doc-whx/whx.github.io/"
languageCode = "zh-CN"
title = "雅韵浮生"
theme = "DoIt"
[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 3

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
# 头像配置
[params.home.profile]
  # Gravatar 邮箱, 用于优先在主页显示的头像
  gravatarEmail = "wanghanxu1@gmail.com"
  # 主页显示头像的 URL
  avatarURL = "/images/avatar.webp"
  # 头像的链接指向的 URL
  avatarLinkURL = "https://doc-whx.github.io/whx.github.io/"
  # 主页显示的网站副标题
  subtitle = "行到水穷处，坐看云起时。"
  # 是否为副标题显示打字机动画
  typeit = true
  # 是否显示社交账号
  social = true
# 主页的社交信息设置
[params.social]
  GitHub = "Doc-whx/"
  Email = "wanghanxu1@gmail.com"
  Zhihu = "xxxx"
  Douban = "xxxx"
  Weibo = "xxxx"
  RSS = true
# 搜索引擎设置
[params.search]
  enable = true
  # 搜索引擎的类型 ("algolia", "fuse")
  type = "fuse"
  # 文章内容最长索引长度
  contentLength = 4000
  # 搜索框的占位提示语
  placeholder = "搜索文章标题或内容..."
  # DoIt 新增 | 0.2.1 最大结果数目
  maxResultLength = 10
  # DoIt 新增 | 0.2.3 结果内容片段长度
  snippetLength = 50
  # DoIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
  highlightTag = "em"
  # DoIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
  absoluteURL = false
  [params.search.algolia]
    index = ""
    appID = ""
    searchKey = ""
  [params.search.fuse]
    # DoIt 新增 | 0.2.12 https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = false
    useExtendedSearch = false
    ignoreFieldNorm = false
